package pl.pjaneczek.entity;
// Generated 2016-01-23 20:56:59 by Hibernate Tools 4.3.1



/**
 * Archives generated by hbm2java
 */
public class Archives  implements java.io.Serializable {


     private int id;
     private String content;
     private String userId;

    public Archives() {
    }

	
    public Archives(int id) {
        this.id = id;
    }
    public Archives(int id, String content, String userId) {
       this.id = id;
       this.content = content;
       this.userId = userId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }




}


