package pl.pjaneczek.entity;
// Generated 2016-01-23 20:56:59 by Hibernate Tools 4.3.1

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

    private int id;
    private String content;
    private String userId;
    private String userName;

    public Message() {
    }

    public Message(int id) {
        this.id = id;
    }

    public Message(int id, String content, String userId) {
        this.id = id;
        this.content = content;
        this.userId = userId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

}
