package pl.pjaneczek.entity;
// Generated 2016-01-23 20:56:59 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Table;




/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String mail;
     private Boolean isLogin;
     private String login;
     private String password;

    public User() {
    }

	
    public User(int id) {
        this.id = id;
    }
    public User(int id, String firstName, String lastName, String mail, Boolean isLogin, String login, String password) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.mail = mail;
       this.isLogin = isLogin;
       this.login = login;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Boolean getIsLogin() {
        return this.isLogin;
    }
    
    public void setIsLogin(Boolean isLogin) {
        this.isLogin = isLogin;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


